### ISSUE TITLE
Update image URL in CSS to point to local image in project

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/project-review-test#10]
[In the CSS](https://github.com/ericandrewlewis/project-review-test/blob/master/resources/css/style.css#L17) a web URL is referenced for the title bar background

```css
#titlebar {
    font-size: 100px;
    font-weight: bold;
    color: khaki;
    text-align: center;
    background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}
```

Make sure to update the url here to be a file url pointing to this pattern.jpeg file that's contained in your project.
