### ISSUE TITLE
Consider an alternative approach for the background color

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/project-review-test#8]
You define this CSS ruleset:

```css
body {
    background: radial-gradient(circle, #999966, #adad85, #ccccb3);
    font-family: Helvetica, sans-serif;
}
```

Nice! I like the idea here, definitely adds some flair to this otherwise visually boring site. If I can make a recommendation, I think it would look even better if you set the height and width of the container div and then set the background color to white with a slight opacity. Here's an example of what I mean, except with a different opacity and background color http://prntscr.com/ektx0a
