### ISSUE TITLE
Don't use vw

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/project-review-test#9]
I notice you use the `vw` unit [in your CSS](https://github.com/ericandrewlewis/project-review-test/blob/master/resources/css/style.css#L8)

```css
.container {
    width: 70vw;
    margin: 0 auto;
}
```

`vw` as a unit of measurement doesn't get used all that often http://stackoverflow.com/questions/2763591/which-unit-i-should-use-in-css-while-designing-web-page
